### ISSUE TITLE
Unauthorised SKU requests

### ISSUE THREAD

**Issue by mateuszkocz** [commercelayer/contentful-extension#1]
Hello,

While testing the extension I've run into a problem of unauthorised SKU requests. Extension fetches a token that seems to not be permitted to get the SKUs list.

![Screenshot 2019-09-02 at 08 22 09](https://user-images.githubusercontent.com/1478684/64094086-d709b880-cd5a-11e9-8d2b-b25fb4fe11f9.png)

After fiddling with API requests manually I've found the parameter `scope` seems to be required (even though the extension sends `client_secret`). Token with this scope fetches SKUs correctly.

Knowing that, I've hardcoded the scope into the extension's code to make it work in my Contentful installation.

```diff
created: function() {
  axios
    .post(`${this.endpoint}/oauth/token`, {
      grant_type: 'client_credentials',
      client_id: extension.parameters.instance.clientID,
      client_secret: extension.parameters.instance.clientSecret,
+     scope: "market:1230"
    })
```

What seems to be an actionable task is either:

1. Allow tokens with `client_secret` to fetch SKUs.
2. Add another configuration option in the extension to pass the market ID.

**Comment by fconforti** [comment]
Hello Mateusz,

Can you tell me which application **kind** you are using?

Thanks,
F.

**Comment by mateuszkocz** [comment]
@fconforti Thanks for the reply. As you probably already understood, I was using the wrong kind (channel). 🤦‍♂  Creating a "contentful" application works great.

Sorry for the false alarm. 🙇

**Comment by fconforti** [comment]
No problem, Mateusz!

Cheers,
F.
